import { PATH } from '#constants/path';
import { Inter } from 'next/font/google';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React from 'react';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
   const router = useRouter();
   React.useEffect(() => {
      router.replace(PATH.main);
   }, []);
   return (
      <>
         <Head>
            <title>My VIIX</title>
            <meta name='description' content='Generated by create next app' />
            <meta name='viewport' content='width=device-width, initial-scale=1' />
            <link rel='icon' href='/favicon.ico' />
         </Head>
         <main>
            <div>메인으로 이동하세요</div>
         </main>
      </>
   );
}
